"""add new user group model in model

Revision ID: 629b0c34d1c4
Revises: 24a7e3d05fdb
Create Date: 2023-06-26 18:04:16.096079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '629b0c34d1c4'
down_revision = '24a7e3d05fdb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usergroup',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('group_no', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usergroup')
    # ### end Alembic commands ###
